services:
  vscode-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      # - PROXY_DOMAIN=code-server.my.domain optional
      # - DEFAULT_WORKSPACE=/config/workspace optional
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    env_file:
      - .env

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped